--- #YAML:1.0
name:               App-Toodledo
version:            2.10
abstract:           Interacting with the Toodledo task management service.
author:
    - Peter J. Scott <cpan@psdt.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Parse:          0
    Digest::MD5:          0
    File::HomeDir:        0
    JSON:                 0
    LWP::UserAgent:       0
    Moose:                0.93
    MooseX::ClassAttribute:  0.12
    MooseX::Method::Signatures:  0.37
    Package::Stash:       0.31
    Test::Exception:      0
    Test::MockModule:     0
    Test::MockObject:     1.20110612
    Test::More:           0
    Test::NoWarnings:     0
    URI::Encode:          0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
