---
abstract: 'Interacting with the Toodledo task management service.'
author:
  - 'Peter J. Scott <cpan@psdt.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Toodledo
no_index:
  directory:
    - t
    - inc
requires:
  Date::Parse: 0
  Digest::MD5: 0
  File::HomeDir: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0.93
  MooseX::ClassAttribute: 0.12
  MooseX::Log::Log4perl: 0
  MooseX::Method::Signatures: 0.37
  Package::Stash: 0.31
  Test::Exception: 0
  Test::MockModule: 0
  Test::MockObject: 1.20110612
  Test::More: 0
  Test::NoWarnings: 0
  URI::Encode: 0
  YAML: 0.79
version: 2.12
